# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

A_count <- function(n, h, r) {
    .Call(`_bclc_A_count`, n, h, r)
}

B_count <- function(n, h, r) {
    .Call(`_bclc_B_count`, n, h, r)
}

D_count <- function(n, r) {
    .Call(`_bclc_D_count`, n, r)
}

build_count_matrices <- function(n_k, Nh_normalize) {
    .Call(`_bclc_build_count_matrices`, n_k, Nh_normalize)
}

eval_true_cov <- function(hvec, beta, lambdas, alphas, sigma) {
    .Call(`_bclc_eval_true_cov`, hvec, beta, lambdas, alphas, sigma)
}

ModifiedExponentialCovariance <- function(grid, sigma = 1.0, alpha1 = 1.0, alpha2 = 1.0, lambda1 = 1.0, lambda2 = 1.0, beta = 0.0) {
    .Call(`_bclc_ModifiedExponentialCovariance`, grid, sigma, alpha1, alpha2, lambda1, lambda2, beta)
}

build_true_Gamma <- function(nvec, beta, lambdas, alphas, sigma) {
    .Call(`_bclc_build_true_Gamma`, nvec, beta, lambdas, alphas, sigma)
}

naive_sample_cov <- function(X, hvec, Nh_normalize = TRUE) {
    .Call(`_bclc_naive_sample_cov`, X, hvec, Nh_normalize)
}

build_Gamma_naive <- function(X, Nh_normalize = TRUE) {
    .Call(`_bclc_build_Gamma_naive`, X, Nh_normalize)
}

build_Sigma_naive <- function(X, Nh_normalize = TRUE) {
    .Call(`_bclc_build_Sigma_naive`, X, Nh_normalize)
}

reshape_Sigma_hat_m <- function(Chat_star_m, m, n1, n2) {
    .Call(`_bclc_reshape_Sigma_hat_m`, Chat_star_m, m, n1, n2)
}

cressiehawkins_semivariogram <- function(X, hvec, Nh_normalize = TRUE) {
    .Call(`_bclc_cressiehawkins_semivariogram`, X, hvec, Nh_normalize)
}

cressiehawkins_cov <- function(X, hvec, Nh_normalize = TRUE) {
    .Call(`_bclc_cressiehawkins_cov`, X, hvec, Nh_normalize)
}

build_Pm <- function(L, m) {
    .Call(`_bclc_build_Pm`, L, m)
}

build_Sm <- function(L1, L2, m) {
    .Call(`_bclc_build_Sm`, L1, L2, m)
}

build_W_m <- function(mat1, mat2, m) {
    .Call(`_bclc_build_W_m`, mat1, mat2, m)
}

bias_corrected_estimator <- function(X, m, Nh_normalize = TRUE) {
    .Call(`_bclc_bias_corrected_estimator`, X, m, Nh_normalize)
}

